build-deps in 'yarn install' step
this makes sense, these are dependencies in the same sense as those pulled
from the internet by yarn install

diff --git a/admin-api-server/script/build-deps b/admin-api-server/script/build-deps
--- a/admin-api-server/script/build-deps
+++ b/admin-api-server/script/build-deps
@@ -4,17 +4,28 @@ cd $SCRIPT_DIR/..
 
 set -u
 
+sig_err_file=`mktemp`
+rm $sig_err_file
 echo "building stm-lib.."
 (
+    trap "echo 'stm-lib build failed' >> $sig_err_file" ERR
+
     cd stm-lib
     yarn build
 ) &
 echo "building api-lib.."
 (
+    trap "echo 'api-lib build failed' >> $sig_err_file" ERR
+
     cd ../lib/api-lib
     yarn build
 ) &
 wait
+[ -f $sig_err_file ] && {
+    cat $sig_err_file
+    rm $sig_err_file
+    exit 1
+}
 
 links=`ls -l node_modules | grep ^l`
 echo "$links" | grep --silent 'kanvas-stm-lib ->' || {
