parralelize test env setup (to speed it up, it's too slow)

diff --git a/admin-api-server/script/test b/admin-api-server/script/test
--- a/admin-api-server/script/test
+++ b/admin-api-server/script/test
@@ -2,11 +2,6 @@
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 cd $SCRIPT_DIR/..
 
-(
-    cd stm-lib
-    yarn build
-)
-
 set -a
 . .env.test
 set +a
@@ -36,20 +31,47 @@ db_docker=`DOCKER_ARGS='-d' DBSETUP_LOG=quiet INIT_QUEPASA=false ./script/local-
 assert_docker_ok $PGPORT
 trap "docker kill $db_docker" EXIT
 
-echo "waiting for testdb setup (admin).. (docker: $db_docker)"
-./script/wait-db
-
-echo "waiting for testdb setup (store).."
-store_env_exec ../store-api-server/script/wait-db
-
-echo "setting up the store db"
+sig_err_file=`mktemp`
+rm $sig_err_file
 (
-    cd $SCRIPT_DIR/../../store-api-server;
-    yarn build || exit 1
+    trap "echo 'yarn linked deps build failed' >> $sig_err_file" ERR
 
-    store_env_exec script/migrate >/dev/null 2>&1 || exit 1
-    store_env_exec psql < script/populate-testdb.sql || exit 1
-) || exit 1
+    echo "ensuring up to date build w/ yarn linked deps (api-lib, etc)..."
+    ./script/build-deps || exit 1
+) &
+(
+    trap "echo 'store build failed' >> $sig_err_file" ERR
+
+    cd $SCRIPT_DIR/../../store-api-server;
+    ./script/build-deps >/dev/null 2>&1 || exit 1
+    yarn build || exit 1
+) &
+(
+    trap "echo 'db setup failed..' >> $sig_err_file" ERR
+
+    echo "waiting for testdb setup (admin).. (docker: $db_docker)"
+    ./script/wait-db
+
+    echo "setting up the store db"
+    (
+        cd "$SCRIPT_DIR/../../store-api-server"
+
+        set -a
+        . .env.test
+        set +a
+
+        echo "waiting for testdb setup (store).."
+        store_env_exec script/wait-db
+        store_env_exec script/migrate >/dev/null 2>&1 || exit 1
+        store_env_exec psql < script/populate-testdb.sql || exit 1
+    ) || exit 1
+) &
+wait
+[ -f $sig_err_file ] && {
+    cat $sig_err_file
+    rm $sig_err_file
+    exit 1
+}
 
 echo "starting the store api in the background"
 # enabling job control with set -m here, this will enforce a new process group
@@ -57,11 +79,7 @@ echo "starting the store api in the background"
 # proper kill of all child processes by kill on process group id.
 set -m
 (
-    cd $SCRIPT_DIR/../../store-api-server
-    yarn build || exit 1
-
-    set -a
-    . .env.test
+    cd "$SCRIPT_DIR/../../store-api-server"
 
     DOTENV_CONFIG_PATH=.env.test store_env_exec yarn run start:prod >/dev/null 2>&1
 ) &
