wip: start embedding the private tezos network into e2e test cases

diff --git a/store-api-server/script/test2 b/store-api-server/script/test2
--- a/store-api-server/script/test2
+++ b/store-api-server/script/test2
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+cd $SCRIPT_DIR/..
 
 set -e
 
@@ -6,6 +8,7 @@ set -a
 . .env.test
 set +a
 export NODE_URL=http://localhost:$FLEXTESA_RPC_PORT
+
 
 tz=`
 docker run \
@@ -21,6 +24,29 @@ TRAP="docker kill $tz"; trap "$TRAP" EXIT
 pg=`DBSETUP_LOG=quiet DOCKER_ARGS='-d' ./script/local-db 2>/dev/null`
 TRAP="$TRAP; docker kill $pg"; trap "$TRAP" EXIT
 
+
+sig_err_file=`mktemp`
+rm $sig_err_file
+(
+    trap "echo 'yarn linked deps build failed' >> $sig_err_file" ERR
+
+    echo "ensuring up to date build w/ yarn linked deps (api-lib, etc)..."
+    ./script/build-deps || exit 1
+    echo build-deps done
+) &
+(
+    trap "echo 'db setup failed' >> $sig_err_file" ERR
+
+    echo "waiting for testdb setup.. (docker: $pg)"
+    ./script/wait-db
+
+    while [ "`HOST=$PGHOST PORT=$PGPORT LOGIN=$PGUSER PASSWORD=$PGPASSWORD ./script/shmig -t postgresql -d $PGDATABASE pending`" != "" ]; do
+        # echo 'testdb setup migrations not done..'
+        sleep 1
+    done
+) &
+
+
 tzInfo=`docker exec local-tezos hangzbox info 2>&1`
 aliceInfo=`echo "$tzInfo" | grep '* ' | head -n 3 | awk '{print $2}'`
 
@@ -28,20 +54,23 @@ export ADMIN_PUBLIC_KEY=`echo "$aliceInfo" | sed '1q;d'`
 export MINTER_TZ_ADDRESS=`echo "$aliceInfo" | sed '2q;d'`
 export ADMIN_PRIVATE_KEY=`echo "$aliceInfo" | sed '3q;d' | awk -F':' '{print $2}'`
 
+bobInfo=`echo "$tzInfo" | grep '* ' | tail -n 3 | awk '{print $2}'`
+export BOB_TZ_ADDRESS=`echo "$bobInfo" | sed '2q;d'`
+
 echo -n "setting up a private tezos network"
 while ! http --quiet :$FLEXTESA_RPC_PORT/chains/main/blocks/head 2>/dev/null; do
-    echo -n '.'
+    # echo -n '.'
     sleep 1
 done
-echo
+# echo
 
 function tz-cli() {
     docker exec local-tezos tezos-client --endpoint http://localhost:20000 "$@"
 }
 
-tz-cli config reset || exit 1
-tz-cli bootstrapped || exit 1
-tz-cli config update || exit 1
+tz-cli config reset
+tz-cli bootstrapped
+tz-cli config update
 
 echo -n "waiting for true bootstrap"
 while ! tz-cli man | grep --quiet originate; do
@@ -55,25 +84,26 @@ mkdir "$tmpdir"
 TRAP="$TRAP; rm -rf $tmpdir"; trap "$TRAP" EXIT
 mintery="$tmpdir/mintery"
 git clone https://github.com/tzConnectBerlin/mintery.git "$tmpdir/mintery" >/dev/null 2>&1
-{
-    cd "$tmpdir/mintery"
-    git checkout allow-custom-dockerargs >/dev/null
 
-    echo "
+cd "$tmpdir/mintery"
+git checkout allow-custom-dockerargs >/dev/null
+
+echo "
 ORIGINATOR_ADDRESS=$MINTER_TZ_ADDRESS
 ORIGINATOR_PUB_KEY=$ADMIN_PUBLIC_KEY
 ORIGINATOR_PRIV_KEY=$ADMIN_PRIVATE_KEY
 " > env
 
-    echo 'deploying the paypoint contract onto the private tezos network..'
-    CONTRACT=paypoint PAYPOINT_RECEIVER_ADDRESS=$MINTER_TZ_ADDRESS BURN_CAP=0.104 DOCKER_ARGS='--network=host' ./script/deploy-contract >/dev/null 2>&1
-    export TEZPAY_PAYPOINT_ADDRESS=`cat env | grep CONTRACT_ADDRESS | awk -F'=' '{print $2}' | sed 's/"//g'`
+echo 'deploying the paypoint contract onto the private tezos network..'
+CONTRACT=paypoint PAYPOINT_RECEIVER_ADDRESS=$MINTER_TZ_ADDRESS BURN_CAP=0.104 DOCKER_ARGS='--network=host' ./script/deploy-contract >/dev/null 2>&1
+export TEZPAY_PAYPOINT_ADDRESS=`cat env | grep CONTRACT_ADDRESS | awk -F'=' '{print $2}' | sed 's/"//g'`
 
-    echo 'deploying the FA2 contract onto the private tezos network..'
-    CONTRACT=fa2 BURN_CAP=0.87725 DOCKER_ARGS='--network=host' ./script/deploy-contract >/dev/null 2>&1
-    export KANVAS_CONTRACT=`cat env | grep CONTRACT_ADDRESS | awk -F'=' '{print $2}' | sed 's/"//g'`
-}
+echo 'deploying the FA2 contract onto the private tezos network..'
+CONTRACT=fa2 BURN_CAP=0.87725 DOCKER_ARGS='--network=host' ./script/deploy-contract >/dev/null 2>&1
+export KANVAS_CONTRACT=`cat env | grep CONTRACT_ADDRESS | awk -F'=' '{print $2}' | sed 's/"//g'`
+
 echo "$TEZPAY_PAYPOINT_ADDRESS,$KANVAS_CONTRACT"
+cd $SCRIPT_DIR/..
 
 qp=`
 docker run \
@@ -85,6 +115,53 @@ docker run \
     --contracts onchain_kanvas=$KANVAS_CONTRACT \
     --contracts paypoint=$TEZPAY_PAYPOINT_ADDRESS \
     --allowed-unbootstrapped-offset 0s`
-TRAP="$TRAP; docker kill $qp"; trap "$TRAP" EXIT
+TRAP="docker kill $qp; $TRAP"; trap "$TRAP" EXIT
 
-sleep 5
+mkdir "$tmpdir"/config
+cat <<EOF > $tmpdir/config/peppermint.json
+{
+    "batchSize": 110,
+    "confirmations": 2,
+    "timeout": 300,
+    "privateKey": "$ADMIN_PRIVATE_KEY",
+    "rpcUrl": "$NODE_URL",
+    "pollingDelay": 1000,
+    "dbConnection": {
+            "user": "$PGUSER",
+            "password": "$PGPASSWORD",
+            "host": "localhost",
+            "port": $PGPORT,
+            "database": "$PGDATABASE"
+    },
+    "handlers": {
+        "nft": {
+            "handler": "MultiassetHandler",
+            "args": {
+                "contract_address": "$KANVAS_CONTRACT"
+            }
+        }
+    }
+}
+EOF
+pm=`
+docker run \
+    --detach \
+    --network=host \
+    --mount type=bind,source="$PWD/$tmpdir"/config/peppermint.json,target=/build/config.json \
+    ghcr.io/tzconnectberlin/peppermint:1.2
+`
+TRAP="docker kill $pm; $TRAP"; trap "$TRAP" EXIT
+
+wait
+[ -f $sig_err_file ] && {
+    cat $sig_err_file
+    rm $sig_err_file
+    exit 1
+}
+
+mkdir -p test/coverage
+node --experimental-vm-modules node_modules/.bin/jest "$@" --coverage | tee test/coverage/summary.txt || exit 1
+sed -n '/^-----/,$p' test/coverage/summary.txt > test/coverage/summary_.txt
+head -n 4 test/coverage/summary_.txt | awk -F '|' '{print $2 $3 $4 $5}'
+sed 's/^/\n/' test/coverage/summary_.txt > test/coverage/summary.txt
+rm test/coverage/summary_.txt
